"""Pure FrameNest domain primitives."""

from kronika.domain.devices import Device, FrameNestDeviceError
from kronika.domain.identities import (
    DeviceId,
    FrameNestIdentityError,
    LibraryId,
    MediaByteIdentityId,
    MediaId,
    MediaLocationId,
    SeriesId,
    StorageVolumeId,
)
from kronika.domain.libraries import (
    FrameNestLibraryError,
    FrameNestLibraryRootError,
    Library,
    LibraryPathFlavor,
    LibraryRoot,
)
from kronika.domain.media import (
    FrameNestMediaError,
    FrameNestMediaLocationError,
    FrameNestMediaRelativePathError,
    LogicalMedia,
    MediaKind,
    MediaLocation,
    MediaLocationAvailability,
    MediaRelativePath,
)
from kronika.domain.media_byte_identities import (
    FrameNestMediaByteIdentityError,
    MediaByteIdentity,
    validate_media_byte_identity_evidence,
)
from kronika.domain.media_metadata import (
    CanonicalTag,
    CanonicalTagDisplayName,
    CanonicalTagKey,
    CollectionState,
    derive_collection_state,
    FrameNestMediaMetadataError,
    MediaCollectionKey,
    MediaDescription,
    MediaDisplayTitle,
    MediaMetadata,
    PROCESSED_COLLECTION_KEY,
)

__all__ = [
    "Device",
    "DeviceId",
    "FrameNestDeviceError",
    "FrameNestIdentityError",
    "FrameNestLibraryError",
    "FrameNestLibraryRootError",
    "FrameNestMediaError",
    "FrameNestMediaByteIdentityError",
    "FrameNestMediaLocationError",
    "FrameNestMediaMetadataError",
    "FrameNestMediaRelativePathError",
    "Library",
    "LibraryId",
    "LibraryPathFlavor",
    "LibraryRoot",
    "LogicalMedia",
    "MediaByteIdentity",
    "MediaByteIdentityId",
    "MediaId",
    "MediaKind",
    "MediaLocation",
    "MediaLocationAvailability",
    "MediaLocationId",
    "MediaRelativePath",
    "CanonicalTag",
    "CanonicalTagDisplayName",
    "CanonicalTagKey",
    "CollectionState",
    "derive_collection_state",
    "MediaCollectionKey",
    "MediaDescription",
    "MediaDisplayTitle",
    "MediaMetadata",
    "PROCESSED_COLLECTION_KEY",
    "SeriesId",
    "StorageVolumeId",
    "validate_media_byte_identity_evidence",
]
